name: Blog CI

on:
  workflow_dispatch:
  push:
    branches-ignore: ["main", "test", "staging"]
    paths:
      - "src/main/java/**"
      - "src/main/resources/**"
      - "pom.xml"
      - "Dockerfile"
  pull_request:
    branches: ["main", "test", "staging"]
    paths:
      - "src/main/java/**"
      - "src/main/resources/**"
      - "pom.xml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=nt114-specializedproject
            -Dsonar.organization=nt114-specializedproject
            -Dsonar.java.binaries=target/classes
            -Dsonar.ci.autoconfig.disabled=true